### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mozizhao** [suvratapte/Maurice-Bach-Notes#2]
In chapter three, section "structure of the buffer pool", there is a typo. "Therefore, if the kernel wants a particular buffer, it will search it on the _has_ queue."

**Comment by suvratapte** [comment]
Thanks for reporting. :)
I have fixed it in this commit: https://github.com/suvratapte/Maurice-Bach-Notes/commit/b0a4a3bd96785aa7a7fdc670a641bdc34cbae799.
